"""empty message

Revision ID: 8b8a1aa1838c
Revises: 
Create Date: 2020-01-10 04:22:33.287067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b8a1aa1838c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('for_recruiter', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('job_seeker', 'current_company',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('job_seeker', 'role',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_seeker', 'role',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('job_seeker', 'current_company',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_table('verification')
    # ### end Alembic commands ###
