"""empty message

Revision ID: 9185a82df7f1
Revises: b8859b2f85a0
Create Date: 2020-01-11 00:03:28.946929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9185a82df7f1'
down_revision = 'b8859b2f85a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employment_details', 'place')
    op.add_column('job_posts', sa.Column('locations', sa.String(length=200), nullable=True))
    op.drop_column('job_posts', 'loactions')
    op.drop_column('job_seeker', 'place')
    op.drop_column('job_seeker', 'role')
    op.drop_column('job_seeker', 'current_company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_seeker', sa.Column('current_company', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('job_seeker', sa.Column('role', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('job_seeker', sa.Column('place', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('job_posts', sa.Column('loactions', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('job_posts', 'locations')
    op.add_column('employment_details', sa.Column('place', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
