"""empty message

Revision ID: f10db39f57f8
Revises: 6f53f1693fbd
Create Date: 2020-01-11 12:58:35.141076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f10db39f57f8'
down_revision = '6f53f1693fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_seeker', 'place')
    op.drop_column('recruiter', 'place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiter', sa.Column('place', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('job_seeker', sa.Column('place', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
